server:
  port: 8500

spring:
  application:
    name: springcloud-eureka-client-product-consumer-8500

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8300/eureka #EurekaServer地址