feign:
  client:
    config:
      default:
        # 设置openfeign客户端连接服务端超时时间
        connectTimeout: 3000
        # 设置openfeign客户端调用超时时间，openfeign默认的调用超时时间为1s
        readTimeout: 4000
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.wangc.springcloud.service.OrderService: debug