server:
  port: 9100

spring:
  application:
    name: gateway-eureka-9100
  cloud:
    gateway:
      discovery:
        locator:
#          enabled: true # 开启服务注册中心服务发现
          lower-case-service-id: true # 启用服务实例id名称小写支持
      routes:
        - id: product-provider
          uri: lb://springcloud-eureka-client-product-provider-8400
          predicates:
            - Path=/product/provider/**
        - id: product-consumer
          uri: lb://springcloud-eureka-client-product-consumer-8500
          predicates:
            - Path=/product/consumer/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8300/eureka #Eureka服务获取地址
      defaultZone: http://localhost:8300/eureka/ #Eureka服务获取地址

logging:
  level:
    org.springframework.cloud.gateway: debug # 配置Gateway日志等级，输出转发细节日志
