server:
  port: 8400

spring:
  application:
    name: springcloud-eureka-client-product-provider-8400
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.243.155:3306/springcloud?useUnicode=true&characterEncoding=utf-8&&userSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml # Mybatis 映射文件位置
  type-aliases-package: com.wangc.springcloud.entity # 表对应的实体类包

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8300/eureka/ #Eureka地址