server:
  port: 8400

spring:
  profiles:
    # mac对应家里
    active: wins
  application:
    name: springcloud-eureka-client-product-provider-8400

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml # Mybatis 映射文件位置
  type-aliases-package: com.wangc.springcloud.entity # 表对应的实体类包

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8300/eureka/ #Eureka地址